kind: pipeline
name: drone-ecr-registry-plugin

workspace:
  base: /go
  path: src/github.com/davidbyttow/drone-ecr-registry-plugin

steps:
- name: test
  image: golang:latest
  environment:
  commands:
    - GO111MODULE=on go test -v ./...
  when:
    event:
      - push
      - pull_request

- name: build
  image: golang:latest
  commands:
    - make build
  when:
    event:
      - push
      - pull_request

- name: publish
  image: plugins/ecr
  settings:
    registry: 873922239110.dkr.ecr.eu-central-1.amazonaws.com
    region: eu-central-1
    repo: 873922239110.dkr.ecr.eu-central-1.amazonaws.com/drone-ecr-registry-plugin
    tags:
    - latest
    - "git_${DRONE_COMMIT_SHA:0:8}"
    - "drone_${DRONE_BUILD_NUMBER}"
  when:
    event:
      - push
      - tag
    branch:
      - master
